### ISSUE TITLE
need release notes with each release

### ISSUE THREAD

**Issue by anupparikh** [biolab/orange3-single-cell#115]
the notes should display first time new version is opened.

**Comment by BlazZupan** [comment]
I will change the current CHANGELOG to "What's new" style.

**Comment by BlazZupan** [comment]
I have updated the descriptions in the change log. The ideas is that the text from this file could be automatically shown wherever we display the information about the last version of the add-on or scOrange. @anupparikh, please review #129.

**Comment by anupparikh** [comment]
i like the new style.

**Comment by anupparikh** [comment]
done.
