### ISSUE TITLE
Load Data: input of the data in 10x format

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#117]
##### Expected behavior

Load data should load the data from 10x format. The data in this format comes as MatrixMarket matrix and the suffix is mtx. Provide support for this format. When the user chooses the file in this format (suffix mtx), disable the "Headers and Row Labels" section of the GUI, as this format does not include the annotations and these, if the user wants to include them, are provided in separate files.

10x data files and annotation files are in most cases located in the same directory. After choosing the data file, the next user's action is to choose the annotation file. For annotation files, a file dialog should then open in the same directory as the one where the user has located the data file.

##### Actual behavior

Currently, mtx is not supported by the widget.

##### Steps to reproduce the behavior

Try loading the example 10x data sets.

**Comment by ales-erjavec** [comment]
Just to double check this is to load 10x [Gene-Barcode Matrices](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices)

Then the genes.tsv and barcodes.tsv need to be read unconditionally.

**Comment by BlazZupan** [comment]
@ales-erjavec true, it would need genes.tsv and barcodes.tsv, but could load the matrix (data) anyway without any annotation as well. This would not allow for any interpretation, but the data would still be prone for inspection or even for analysis (say, are there any clusters?).
