### ISSUE TITLE
Datasets: include Organism column, rename some columns

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#121]
##### Expected behavior
After column "Variables" add column "Organism" that shows short name of the organism (like, Human, Mouse). Start with upper-case.

Rename:
Instances -> Cells
Varibles -> Genes

Attach taxid to as hint to the output data (use data_hints.set_hint).

Set data hint to output data that tells that gene names are in columns.

Test if above works in combination with Gene Ontology (this has to work with no special setting).

**Comment by lanzagar** [comment]
Done in #125.
Some follow-up needed as described in #138.
