### ISSUE TITLE
Batch effect normalization

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-single-cell#123]
Current normalization only equalizes median expression levels of individual cells or groups. It would be important to have a linear model-based normalization to account for potential confounding variables (i.e. batch effects). One option is to treat each gene individually and subtract the variance explained by one or more covariates. 

See example:
http://satijalab.org/seurat/cell_cycle_vignette.html

**Comment by mstrazar** [comment]
Filed under #131 .

**Comment by anupparikh** [comment]
How do I quantify the effect of normalizing before and after? 

* A number (r^2) showing the magnitude of batch effect per class before normalization
* after normalization, a number (within group vs between group distance) showing how well normalization worked

**Comment by BlazZupan** [comment]
An example data set and the workflow with the same results as in http://satijalab.org/seurat/cell_cycle_vignette.html would be great.

**Comment by lanzagar** [comment]
Implemented in #131 
Example workflow to be added (see #134)
