### ISSUE TITLE
Analysis of Clusters

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#127]
In single cell analysis, clusters delineate a set of cells with some common properties. We would like to understand what is common to the cells in the same cluster and why this group is different from the others. In particular, we would like to see which genes are specific to a cluster. Almost every paper in this field uses some technique to explain clusters and usually links this to a particular visualization. Here is an example:

![screen shot 2018-03-16 at 12 39 02](https://user-images.githubusercontent.com/726604/37518799-09258540-2917-11e8-89de-895e24551a62.png)

scOrange does not have a visualization that would clearly present the relationship between clusters and genes. An extra useful feature would also be interactivity of such visualization.

**Comment by BlazZupan** [comment]
This also addresses #60.

**Comment by golbog** [comment]
I am a student at University of Computer and Information Science in Ljubljana and I would like to contribute to this project. 
I've already made some basic visualization that roughly resembles and example.
![fig1](https://user-images.githubusercontent.com/17678055/37874824-e0b7a51c-3036-11e8-884e-78443cbe848c.png)

**Comment by BlazZupan** [comment]
Great, @golbog. The graph looks nice. Which procedure have you used for ordering of columns and rows?

**Comment by golbog** [comment]
I used the algorithm described in this blog post: https://gmarti.gitlab.io/ml/2017/09/07/how-to-sort-distance-matrix.html

**Comment by BlazZupan** [comment]
The coming-up widget was just provided an icon, see #158

**Comment by BlazZupan** [comment]
Rafael from Genialis has pointed me to a nice [blog](http://jef.works/blog/2018/04/25/visually-summarizing-differential-gene-expression/) on this, shows some ideas we can include: hoover, combination with a color legend, and plotting differential expression scores as an alternative to "fraction expressed".
