### ISSUE TITLE
An example workflow for batch normalization

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#134]
Add a workflow that exemplifies the utility of the batch normalization. Use the data from http://satijalab.org/seurat/cell_cycle_vignette.html.

**Comment by BlazZupan** [comment]
@mstrazar can you take a look after #131?

**Comment by mstrazar** [comment]
Available on:
Google Drive/Biolab/projekti/scOrange/use-cases-and-workflows/Batch normalization

**Comment by mstrazar** [comment]
Waiting on #147 and  #148 .
