### ISSUE TITLE
Example workflow for loading my own data

### ISSUE THREAD

**Issue by anupparikh** [biolab/orange3-single-cell#135]
* load data from tab matrix
* load data from 10x data

the workflow has to show user how they can upload their own data.
* What formats are supported?

**Comment by astaric** [comment]
Include Gene Name Matches, show how to handle "unmatched genes"

**Comment by anupparikh** [comment]
include cluster analysis and differential expression, and Go ontology

**Comment by BlazZupan** [comment]
Moving this to 0.7 when the loader will be ready (gene name matching, info on gene annotation).
