### ISSUE TITLE
Score Cells: aggregation

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-single-cell#153]
Some enhancements to be added to Score Cells.

1. Enable different aggregation functions (currently, only max is supported): 
Examples: mean, median, conjunction (at some expression threshold)

**Comment by BlazZupan** [comment]
Item 1 has a problem, because it may be hard to compare expressions over different genes. Perhaps the proportion of expressed genes from a list of marker genes would be a better scoring.

**Comment by BlazZupan** [comment]
@mstrazar Please split this issue to two: scoring and subsetting.

**Comment by BlazZupan** [comment]
This issue was resolved with #201, if there are any other ideas for aggregation functions -- that is, other than those that are already implemented -- they should be expressed in separate issues.
