### ISSUE TITLE
Score Cells + Cluster Analysis: Include gene name matching from bioinformatics addon

### ISSUE THREAD

**Issue by astaric** [biolab/orange3-single-cell#176]

**Comment by BlazZupan** [comment]
Related to https://github.com/biolab/orange3-bioinformatics/issues/40, which assumes tagging of the data with where the gene names are stored (header row or column) and what is the name of the vairable/attribute that stores gene ID. The referred issue uses this functionality and embeds it into widget for adding standard (Entrez) IDs to the data. Once this is done, the final fix requires changing of bioinformatics widgets that require the information on gene names (e.g., GO and KEGG).

FIx is also required for widgets from scOrange, including Cluster Analysis and Score Cells.

**Comment by BlazZupan** [comment]
I am closing this issue since related issue at bioinformatics add-on has been closed, see  biolab/orange3-bioinformatics#40
