### ISSUE TITLE
Score Cells: given a set of markers, subset columns

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-single-cell#177]
Given a list of marker genes (typically 10-100s), subset the table columns. This would operate like "Select columns", but the columns would be provided as rows in a table upstream, and assumes too many genes to do it with select columns. 

This is may also be implementable in another widget.

**Comment by BlazZupan** [comment]
This will be implemented under the changes in Gene Sets widget, see https://github.com/biolab/orange3-bioinformatics/issues/65
