### ISSUE TITLE
Load Data: select organism, provide gene id information

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#191]
It would be preferred if Load Data outputs the data with explicit information about the location of gene ids and organism. See Single Cell Datasets for an example and annotation of data as displayed in Data Info widget:

<img width="237" alt="screen shot 2018-05-22 at 09 01 39" src="https://user-images.githubusercontent.com/726604/40346957-c8a010f0-5d9e-11e8-89e8-a3f2e45565c1.png">

Following steps may be necessary to address this issue:
- add Organism selection pane in between Input Data Structure and Sample Data panes. Can copy this pane from current GO Browser (warning: the selection of organism there will be removed since the data sets will carry this information). Make Homo Sapiens a default for any new data file, and remember the selection for the data file name.

<img width="256" alt="screen shot 2018-05-22 at 09 04 27" src="https://user-images.githubusercontent.com/726604/40347105-4a8ebef4-5d9f-11e8-9517-6329d6602c8d.png">

- use the implementations from bioinformatics to convert the gene names to gene IDs, and store IDs in the attribute's attribute "Entrez ID"
- issue warning if less than, say, 80% of genes names have been mapped (e.g., "Entrez IDs found for only 20% of genes", or "No corresponding gene names found in NCBI's Entrez.").

Note that current alternative to this functionality is to use right Gene Name Matcher widget right after Load Data.

**Comment by JakaKokosar** [comment]
This is already implemented in [OWGeneNameMatcher](https://github.com/biolab/orange3-bioinformatics/blob/master/orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py) widget from Orange3-bioinformatics add-on. Requested changes are not needed as they would further complicate widget functionality. 

Also, this makes single-cell even more dependent on bioinformatics add-on.

**Comment by BlazZupan** [comment]
Agreed, no need to duplicate functionality of one widget in the second one. Closing this issue as it has been resolved in the way of combining load data with gene name matching widgets.
