### ISSUE TITLE
Load Data errors

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3-single-cell#193]
##### Single Cell version

0.5.2

The Load Data widget should do more checking for possible problems while opening files and show nicer user errors instead of crashing (send report window).

 I am starting a list here to keep track of problems (but we can make some a stand alone issue if needed)

- [x] 1. opening a .tab.gz file
- [x] 2. changing "Headers and Row Labels" to incorrect values (tested with a .tab file)
- [x] 3. opening an unsupported file (e.g. foo.py)

**Comment by VesnaT** [comment]
Some tests were added in #180, as well as the above error (2. error) was handled.
Additional error handling comes with #202.

**Comment by BlazZupan** [comment]
@lanzagar, can you please check

**Comment by BlazZupan** [comment]
@lanzagar, please suggest the message to be displayed for 2.

**Comment by lanzagar** [comment]
All 3 issues are now resolved. The messages are also ok IMO.
