### ISSUE TITLE
Doesn't install any files

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3-single-cell#219]
```orange3-bioinformatics``` does create widgets, but ```orange3-single-cell``` doesn't for some reason.

**Comment by BlazZupan** [comment]
@yurivict sorry, we are not able to replicate your issue. Could you be more specific how are you running single cell orange, and include the output from terminal window. Notice also that, as for stand-alone installation, there is new release (version 0.8) coming, so you may try that one.

For now, I am closing this issue. You can reopen it with any more details.
