### ISSUE TITLE
Cluster Analysis widget

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#229]
This is a description of new widget for cluster analysis. Input of the widget is a gene expression data set with cells (rows) and genes (columns) that includes an extra class or meta variable denoting cell clusters. The widget displays differentially expressed genes that characterize the cluster, and corresponding gene terms that describe differentially expressed genes. User can select one or more clusters, instructing the widget to output a table containing the corresponding cells and (union) of corresponding genes.

Cluster Analysis widget that already exists in scOrange should be renamed to Dot Matrix Analysis (or something more appropriate) and should be kept in the distribution.

![cluster analysis](https://user-images.githubusercontent.com/726604/42133394-cfd1b3c4-7d29-11e8-8f12-7b89d0662f1d.png)

**Comment by mstrazar** [comment]
Currently, we are also missing the option to select the directionality of the test (over- or under- expressed) genes, i.e. different alternative hypotheses (two-sided, greater, lesser). This is a problem in the case of two clusters, as the same set of genes (and terms) will be displayed for both clusters.

I suggest either defaulting to 'Greater' of adding a choice like this:

Alternative hypothesis
(o) Two-sided
() Less
() Greater

**Comment by BlazZupan** [comment]
@mstrazar, please move your comment into a separate issue, to be fixed in next releases. It is not just the problem of this widget, but of the code in the library.
