### ISSUE TITLE
Broken links and outdated widgets in sample workflows on Welcome Screen

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#241]
Titles of the tutorial workflows have changed to reflect the fact that they are displayed in their alphabetical order in the list of templates. A three letter digit was added to each name. In the welcome screen, these workflows are referred to with exact names, and these links were broken in release 0.7

**Comment by mstrazar** [comment]
Showcase workflows must be also be updated to use the new Preprocess/Batch Effect Removal widgets, etc.
