### ISSUE TITLE
Redesign of Save widget (Orange)

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#242]
The current implementation of Save widget in Orange is useful since we would often save intermediate results of the single cell data analysis, either by saving the results of preprocessing or saving the data in the format readable by some other analysis environments. Orange now allows to save also binary formats, like pickled and zipped data, but the interface is non-intuitive requiring the user to now exactly the right suffix for the associated data type. Instead, in the new interface, the user provides the name of the file and chooses the type of the output (e.g., Excel, CSV with chosen delimiter, Orange native, Orange pickled, Orange pickled zipped).

This issue should be addressed by a special issue and corresponding code in Orange.

**Comment by lanzagar** [comment]
Issue opened in Orange: https://github.com/biolab/orange3/issues/3136

**Comment by lanzagar** [comment]
Implemented and merged in Orange https://github.com/biolab/orange3/pull/3147
