### ISSUE TITLE
Batch Effect Removal: new widget

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#250]
Redesign Normalize widget and, functionally, retain its bottom portion. The new look of the widget is

![screen shot 2018-07-25 at 11 28 13](https://user-images.githubusercontent.com/726604/43192502-fdad5654-8ffd-11e8-9634-34d29d4d4194.png)

For now, keep the icon. After the change, Normalize widget should be removed.

**Comment by mstrazar** [comment]
Not to forget: we need to discuss a way to correctly implement linear regression-based correction with skipping zeros.
