### ISSUE TITLE
OWDotMatrix: unhashable type: 'list'

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3-single-cell#308]
##### Steps to reproduce the behaviour

File -> iris -> Dot Matrix -> Send report

##### Additional info (worksheets, data, screenshots, ...)
One can not use list to get variables from a domain.

```
columns = self.columns
if columns in self.data.domain:
    columns = self.data.domain[columns]
```

Thus:

```TypeError:  unhashable type: 'list'
  Module "Orange.widgets.report.report", line 41, in show_report

    self.create_report_html()
  Module "Orange.widgets.report.report", line 66, in create_report_html

    self.send_report()
  Module "orangecontrib.single_cell.widgets.owdotmatrix", line 251, in send_report

    if columns in self.data.domain:
  Module "Orange.data.domain", line 282, in __contains__

    return item in self._indices```

**Comment by JakaKokosar** [comment]
@jurijsteblaj, since you are the one working on this widget, can you look at this?

**Comment by JakaKokosar** [comment]
Sentry issue: [ORANGE3-SINGLE-CELL-W](https://sentry.io/biolab/orange3-single-cell/issues/738067176/)

**Comment by jurijsteblaj** [comment]
I think we never specified and implemented reports for this widget so this is just some code which was taken from some other widget when initially making this one.

If we need reports for this widget we should probably specify what we want in another issue. Until then I will just remove the button by removing the `send_report` method.
