### ISSUE TITLE
OWScoreGenes: IndexError:  index is out of bounds 

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3-single-cell#310]
https://sentry.io/biolab/orange3-single-cell/issues/704431463/

Selected rows are stored in OWRank.selected_rows variable. If the model changes (new signal) model tries to select rows, that are not in the model and IndexError is raised.

##### Steps to reproduce the behaviour

Select all rows in score genes widget and then change the input data.

##### Additional info (worksheets, data, screenshots, ...)
```
IndexError:  index 12461 is out of bounds for axis 1 with size 10442
  Module "Orange.canvas.scheme.widgetsscheme", line 972, in process_signals_for_widget

    widget.handleNewSignals()
  Module "orangecontrib.single_cell.widgets.owscoregenes", line 456, in handleNewSignals

    self.updateScores()
  Module "orangecontrib.single_cell.widgets.owscoregenes", line 563, in updateScores

    self.autoSelection()
  Module "orangecontrib.single_cell.widgets.owscoregenes", line 601, in autoSelection

    for row in model.mapFromSourceRows(self.selected_rows):
  Module "Orange.widgets.utils.itemmodels", line 158, in mapFromSourceRows

    new_rows = self.__sortIndInv[rows]
```

**Comment by NejcDebevec** [comment]
I can't reproduce the error. Closed for now will reopen if it appears again.
