### ISSUE TITLE
scOrange 0.9 Mac package does not respect requirements.txt

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3-single-cell#325]
##### Single Cell version
0.9 dmg

##### Actual behavior
0.9 dmg includes PyQt5==5.11.3. This has some problems, like biolab/orange3#3546

That seems strange, because installer/macos/requirements.txt differ from what I get if I do pip freeze on the app from dmg. How was this dmg built?

Unless there is an another repository with scripts for building scOrange package, the current builds are non-reproducible and the next ones should be made differently.

**Comment by JakaKokosar** [comment]
Sorry for the confusion. Release 1.0 now respects the requirements provided in this [file](https://github.com/biolab/orange3-single-cell/blob/master/installer/macos/requirements.txt). 

Closing this issue.
