### ISSUE TITLE
Issues loading data from Excel in scOrange on a Mac OS

### ISSUE THREAD

**Issue by YuriB85** [biolab/orange3-single-cell#365]
I am OSX 10.14.6 user and I am having difficulties opening Excel files in scOrange (v. 1.3.0).

I have tried multiple Excel files and even following the YouTube video "Single Cell Orange 03: Loading Single Cell Data from Tab-Delimited Files" I downloaded the file Dicty.xlsx from the source linked in YouTube, but it does not open. I've tried also OSX 10.13.6 and the same issue occurs. On the other hand, It works perfectly on a Win10 PC.

**Comment by YuriB85** [comment]
This is what I get if I try following the example in the tutorial:

<img width="1279" alt="Screenshot 2019-09-14 at 4 04 54 PM" src="https://user-images.githubusercontent.com/55202978/64905351-78a0ea80-d709-11e9-9d23-dc10fba75e62.png">

I downloaded the scOrange installer from the website. 

Thanks.

**Comment by JakaKokosar** [comment]
@VesnaT  Can you maybe look at this when you have the time?

**Comment by VesnaT** [comment]
I'm looking at it, but can't reproduce it.

**Comment by JakaKokosar** [comment]
Installer ships with a version of xlrd which does not support python 37. This is supported as of [version 1.2.0](https://github.com/python-excel/xlrd/commit/6db75c94e6869384815b9663b1f2a36b211c668b#diff-fed77448f29b992f3ad4fc8670ec3812R9). 

@YuriB85 Thank you for reporting this. I will update the installer and let you know when its done.
