### ISSUE TITLE
GEO Data Sets widget

### ISSUE THREAD

**Issue by YuriB85** [biolab/orange3-single-cell#366]
I am trying to access some GEO datasets through the GEO DataSets widget but I cannot find any of the data sets I am interested in. Is this widget supposed to be able to access all the  NCBI data sets or only a selected group? Many thanks.

**Comment by BlazZupan** [comment]
Can you tell us which particular dataset from GEO DataSets collection are your looking for that would not be included in the list provided by the Orange's GEO Data Sets widget? Please note that this widget provides access only to the data in the GEO DataSets collection, a curated collection from GEO.

**Comment by YuriB85** [comment]
@BlazZupan thank you for your reply and clarification. These are the datasets I'm looking for: GSE10245, GSE10799, GSE18842, GSE28571, GSE31210, GSE33356, GSE50081.

**Comment by BlazZupan** [comment]
@YuriB85, the IDs that you are referring to (GSE10245, ...) do not refer to data that is included in [GEO DataSets](https://www.ncbi.nlm.nih.gov/geo/info/datasets.html). The IDs of the data included in this collection starts with GDS. Orange's widget GEO Data Sets includes only the GEO data included in the DataSets collection. For other data from GEO, there is no special widget in Orange: please import them by preparing an associated tab-delimited file.
