### ISSUE TITLE
Marker genes

### ISSUE THREAD

**Issue by YuriB85** [biolab/orange3-single-cell#367]
Hi, I am following the example "Exploring the Fruit Fly Olfactory System" and using the "Marker genes" widget I cannot retrieve acj6. 
![image](https://user-images.githubusercontent.com/55202978/65213832-495bf600-dada-11e9-8c4b-b358f3d48fcc.png)
It seems that the only organisms I can choose from are "Human" and "Mouse". I tried to use the "Databases Update" but without any luck. 
Should I import these marker genes manually from Li et al. (2017)? Thank you in advance.

**Comment by BlazZupan** [comment]
Thank you for your writing. Reported is not a bug. Marker Genes widgets presents marker genes from two databases, [CellMarker](http://biocc.hrbmu.edu.cn/CellMarker) and Panglao that currently include only markers for human and mouse. To include marker genes from some other source, including the publication, create your own data file with genes and cell types, read the file with File widget, and pass them through Genes widget to obtain associated Entrez IDs.

**Comment by YuriB85** [comment]
Hello, I was wondering whether you are planning to add any functionality in scOrange to handle TCGA datasets. Specifically, I am interested in downloading gene expression datasets, as well as clinical annotation files and perform differential gene expression analyses between tumor patients and healthy control and to conduct survival analyses to test the prognostic value of particular gene panels. Many thanks in advance.



________________________________

Important: This email is confidential and may be privileged. If you are not the intended recipient, please delete it and notify us immediately; you should not copy or use it for any purpose, nor disclose its contents to any other person. Thank you.

**Comment by ajdapretnar** [comment]
@YuriB85 It is best if you open such questions as a new issue and tag it with 'Question' or something similar.
