### ISSUE TITLE
The Cancer Genome Atlas (TCGA) datasets

### ISSUE THREAD

**Issue by YuriB85** [biolab/orange3-single-cell#375]
Hello, I was wondering whether you are planning to add any functionality in scOrange to handle TCGA datasets. Specifically, I am interested in downloading gene expression datasets, as well as clinical annotation files and perform differential gene expression analyses between tumor patients and healthy controls, to conduct survival analyses to test the prognostic value of particular gene signatures and perform computational classification of Tumor vs Normal based on the identified gene signatures. Many thanks in advance.

**Comment by BlazZupan** [comment]
YutiB85, sorry, no. Our focus has now shifted to core Orange.
