### ISSUE TITLE
Load Data: incorrect assignment of source file

### ISSUE THREAD

**Issue by M-860307** [biolab/orange3-single-cell#389]
**What's wrong?**
<In the t-SNE interface after loading two matrix.mtx data for scRNA analyses, the t-SNE interface could not colors the cells according to the source. When we colored the cells using the source choice, the t-SNE figure still exhibits one color, and the legend only shows one matrix.mtx data. >

**How can we reproduce the problem?** 
<In the t-SNE interface after loading two matrix.mtx data for scRNA analyses, the t-SNE interface could not colors the cells according to the source. When we colored the cells using the source choice, the t-SNE figure still exhibits one color, and the legend only shows only one matrix.mtx data. >

**What's your environment?**
- Operating system: Windows 10
- Orange version: The latest 3-3.32.0-Miniconda-x86_64
- How you installed Orange: according to the protocols

**Comment by M-860307** [comment]
> I'd say it's a bug in Load Data widget, which incorrectly assigns source data. Moving the issue to the corresponding repository.

Thanks very much for your help. Could you please tell us how we could solve this problem in the next step?

**Comment by ajdapretnar** [comment]
If you know how to fix the bug in the Load Data widget, then we are happy to accept a pull request.
If not, someone from the core team who works with sc data needs to check this and submit a fix. @JakaKokosar @pavlin-policar ?

**Comment by M-860307** [comment]
> If you know how to fix the bug in the Load Data widget, then we are happy to accept a pull request. If not, someone from the core team who works with sc data needs to check this and submit a fix. @JakaKokosar @pavlin-policar ?

Yes, as you say, we do not know how to fix the bug in the Load Data widget. So would you please like provide us a fix or tell us other manner to solve this problem?

**Comment by M-860307** [comment]
> If you know how to fix the bug in the Load Data widget, then we are happy to accept a pull request. If not, someone from the core team who works with sc data needs to check this and submit a fix. @JakaKokosar @pavlin-policar ?

Well, we still did not receive your reply. Would you please like tell us how to solve this problem? We are clinical doctors and the Code is very difficult for us. The best way might be that the team could provide the correct version to download for installing. Many thanks for your help.
