### ISSUE TITLE
exploring cell types without predefined list

### ISSUE THREAD

**Issue by anupparikh** [biolab/orange3-single-cell#60]
Need a way to define the top differentially expressed genes between clusters. The cluster variation widget only gets me part of the way. 
I need a p-value or some metric by which I define the top genes that differentiate each cluster. Then I would like to run GO enrichment on that list. 

##### Single Cell version

0.2

##### Orange version

3.9.0

**Comment by lanzagar** [comment]
Cluster Variation widget was removed in #87.
Differential Expression is now the intended way to find d.e. genes and it already gives p-values as requested.

If nobody has any other comments, I think this can be closed.
We did talk about additional refinements/simplifications to the Differential Expression widget, but we should open new issues for those.
