### ISSUE TITLE
file browser widget freezes above all other windows on large file load

### ISSUE THREAD

**Issue by anupparikh** [biolab/orange3-single-cell#75]
##### Single Cell version

0.2.1

##### Orange version

3.9.0

##### Expected behavior
 the file browser window should close after file is selected, and then the loading should start. 

##### Actual behavior
when I select a large file to load from the file browser window freezes above all other windows until the loading finishes. I cannot do anything else until load finishes. 

##### Steps to reproduce the behavior
load a large file in file widget

**Comment by BlazZupan** [comment]
This is a valid Orange-related problem. Can you please open an issue on [Orange issue tracker](https://github.com/biolab/orange3/issues).
